# Generated by Django 5.1.5 on 2025-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='aliases/'),
        ),
    ]
