# Generated by Django 4.0.6 on 2025-02-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_transaction_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date_of_holding'], name='trades_tran_user_id_e9afa0_idx'),
        ),
    ]
